name: adenoma-cell2location
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - anndata==0.11.4
      - cell2location==0.1.5
      - numpy==2.2.6
      - scanpy==1.11.5
      - scipy==1.15.2
      - scvi-tools==1.3.3
      - torch==2.6.0

