name: adenoma-stlearn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.2
  - pandas
  - scikit-learn
  - pip
  - pip:
      - scanpy==1.11.5
      - stlearn==1.2.2

